[package]
name = "wayland-client"
version = "0.20.10"
documentation = "https://smithay.github.io/wayland-rs/wayland_client/"
repository = "https://github.com/smithay/wayland-rs"
authors = ["Victor Berger <victor.berger@m4x.org>"]
license = "MIT"
categories = ["gui", "api-bindings"]
keywords = ["wayland", "client"]
description = "Bindings to the standard C implementation of the wayland protocol, client side."
build = "build.rs"

[badges]
travis-ci = { repository = "smithay/wayland-rs" }

[dependencies]
wayland-commons = { version = "0.20.10", path = "../wayland-commons" }
wayland-sys = { version = "0.20.10", features = ["client"], path = "../wayland-sys", optional = true }
bitflags = "1.0"
libc = "0.2"

[build-dependencies]
wayland-scanner = { version = "0.20.10", path = "../wayland-scanner" }

[dev-dependencies]
byteorder = "1.0"
tempfile = "2.0"

[features]
native_lib = [ "wayland-sys", "wayland-commons/native_lib" ]
dlopen = ["wayland-sys/dlopen", "native_lib"]
egl = ["wayland-sys/egl", "native_lib"]
cursor = ["wayland-sys/cursor", "native_lib"]

